<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Company>Screen Time Native</Company>
    <Product>Screen Time</Product>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
